// Autogenerated by .csproj file. Do not edit, your modifications will be lost after generating file again

namespace TAWLauncher {
    public static partial class Config {
        public static readonly string LoadingLogo = "Resources/large.png";
        public static readonly bool SkipConfigFile = false;
        public static readonly string VersionFileUrl = "null";
        public static readonly string ApplicationZipUrl = "null";
        public static readonly bool AutomaticallyUpdate = false;
        public static readonly string ExeToRun = "null";
        public static readonly bool RunAfterUpdateFinished = false;
        public static readonly bool KeepZipFile = false;
        public static readonly bool KeepLauncherOpen = false;
    }
}
